language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ./patricktalmadge/bootstrapper ./laravel/bundles/bootstrapper
  - echo "<?php return array('bootstrapper' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ./laravel

script: "php artisan test bootstrapper"